### ISSUE TITLE
"pkgfile --update" should create the "/var/cache/pkgfile" directory if it doesn't exist

### ISSUE THREAD

**Issue by cmhe** [falconindy/pkgfile#25]
Since the [FHS](http://www.pathname.com/fhs/2.2/fhs-5.5.html) suggests that applications should recreate everything in "/var/cache/" if those files are deleted, I would suggests that pkgfile should create its cache directory automatically if it doesn't exist.

**Comment by falconindy** [comment]
This doesn't work if you run pkgfike as non-root. Arch Linux's package includes this dir. I'd suggest that if you delete it, you recreate it.

**Comment by cmhe** [comment]
Archs package contains '/var/cache/pkgfile', but with ownership root:root and permissions 775, so non-root users can't write anything into it. So you have to run 'pkgfile --update' as root.

**Comment by falconindy** [comment]
But you can chown it after installation and pacman will respect that...

Reading the FHS page you link, I see no indication that applications should be able to recreate the *directory*, just the data.

**Comment by cmhe** [comment]
Ok. But if you manually chown it, then you should recreate yourself it or chown it again after 'pkgfile --update'.

About the FHS, you are correct, 'directory' is not stated explicitly. Its just what I am used to do. For instance in Debian 'apt-get update' recreates '/var/cache/apt' and in Arch pacman recreates '/var/cache/pacman' automatically. I think most others do this too. So why not pkgfile?
