### ISSUE TITLE
zsh hook breaks command not found message

### ISSUE THREAD

**Issue by mixedCase** [falconindy/pkgfile#28]
When a binary has not been found in a package, the usual message `zsh: command not found: $1` should be shown, and used to be shown.

With an updated Arch install, I don't seem to be get it anymore. Might've been triggered by a database update.

Tested running zsh with no config (via `zsh -f`) and sourcing the hook interactively reproduces the bug just as well as a fully featured config.

**Comment by nl6720** [comment]
It's because zsh 5.3 changed things.

From http://zsh.sourceforge.net/releases.html
> Previously, if the function command_not_found_handler was run in place of a command-not-found error, and the function returned non-zero status, zsh set the status to 127 and printed an error message anyway. Now, the status from the handler is retained and no additional message is printed. The main reasons for this change are that it was not possible to return a non-zero status to the parent shell from a command executed as a replacement, and the new implementation is more consistent with other shells. 

command-not-found.zsh needs to be adjusted to return the error message & code like command-not-found.bash does.

**Comment by falconindy** [comment]
I don't use zsh and I didn't write the hook. Happy to take a patch to fix this.
