### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by mixedCase** [falconindy/pkgfile#30]
I just looked and there hasn't been a release since mid-2014, which has made the official repo's package stagnant. Is there anything blocking it?

**Comment by falconindy** [comment]
No, nothing blocking. 2017 will see a release -- I'm on vacation until mid January.

**Comment by mixedCase** [comment]
@falconindy Any news?

**Comment by falconindy** [comment]
Work, life, etc. Thanks for bumping this.

**Comment by falconindy** [comment]
I've released v17 into the wild.
