### ISSUE TITLE
bash completions lack filename/directory support

### ISSUE THREAD

**Issue by gonzote** [falconindy/pkgfile#31]
90% of my use is the default search mode, with a command like `pkgfile foo` or `pkgfile /path/to/foo` where foo is a filename.  The default completion function won't complete anything other than the program options without running `compopt -o default pkgfile` first.

The same problem exists with specific `-s` or `--search` options: filename targets are never tab-completed.  The completion function needs a well-placed `compopt -o default` or similar to enable completion for filenames.

Thanks!

**Comment by falconindy** [comment]
Old issue is old. It seems odd to me that you want tab completion of existing files for a utility whose main purpose is looking up the ownership of files which likely don't exist on your filesystem. That's the reason why this tab completion doesn't exist.
