### ISSUE TITLE
Feature request: Search in AUR packages

### ISSUE THREAD

**Issue by teras** [falconindy/pkgfile#37]
Hello and thank you for this nice utility.

Is it possible to use it to search in files of installed packages?
Since from my understanding, though, it is not possible to search in AUR packages which are not installed, at least search in packages that are installed and their structure is known.

**Comment by falconindy** [comment]
No, it's not possible.

**Comment by teras** [comment]
I mean, the files are there and searchable with pacman commands, which makes it funny not to be able to search in them

**Comment by falconindy** [comment]
No, it's not funny at all. pkgfile relies on the files databases produced from repositories, and served by mirrors. This implies packages have been built and catalogued in a repo. The AUR provides source code only.

**Comment by falconindy** [comment]
Your original request mentioned AUR packages (which aren't packages at all, but PKGBUILDs), so I commented on the feasibility of pkgfile searching the filelists for AUR packages.

Now you seem to be asking about packages which are installed on your system, for which pkgfile isn't the right tool and there exists no distinction for the source of a package -- pacman does not track provenance. A package is a package is a package. Use pacman to search filelists for installed packages.

**Comment by falconindy** [comment]
> Indeed I am not proficient what alpm .files metadata is, but still extending pkgfile to an ultra tool to search for all possible files, something that tools in other distributions are using, would be very convenient.

As the pkgfile author, I'm telling you that this is out of scope for the project. I'm not sure how you propose to get file lists for packages without building them....

> The problem with AUR files is that nobody keeps track. Since AUR is general a deterministic process, it is possible. The only thing that prohibits it is that nobody spends the resources and the time to do it.

...and I'm not sure you understand how freeform the AUR is if you're calling it a "deterministic process". The AUR is the wild west of PKGBUILDs, and given that they're bash scripts, they can do anything, including being non-deterministic.
