### ISSUE TITLE
/var/cache/pkgfile permissions mismatch after upgrade to 18-1

### ISSUE THREAD

**Issue by RalphCorderoy** [falconindy/pkgfile#39]
I haven't altered /var/cache/pkgfile's permissions in the past, yet...

    $ grep pkgfile /var/log/pacman.log
    [2016-02-14 01:12] [PACMAN] Running 'pacman -S pkgfile'
    [2016-02-14 01:13] [ALPM] installed pkgfile (15-1)
    [2016-02-14 01:13] [ALPM-SCRIPTLET] ==> Run 'pkgfile --update' to initialize the database
    [2017-04-20 11:53] [ALPM] upgraded pkgfile (15-1 -> 17-1)
    [2018-08-07 14:04] [ALPM] warning: directory permissions differ on /var/cache/pkgfile/
    [2018-08-07 14:04] [ALPM] upgraded pkgfile (17-1 -> 18-1)
    $
    $ pacman -Qkk pkgfile
    warning: pkgfile: /var/cache/pkgfile (Permissions mismatch)
    pkgfile: 30 total files, 1 altered file
    $
    $ ls -ld /var/cache/pkgfile
    drwxrwxr-x 2 root root 4096 Aug  8 03:38 /var/cache/pkgfile
    $ zgrep '^\./var/cache/pkgfile ' /var/lib/pacman/local/pkgfile-18-1/mtree
    ./var/cache/pkgfile time=1533489430.0 mode=755 type=dir
    $

It may be due to https://github.com/falconindy/pkgfile/commit/f39b715b9498d977269e16941b23d916c1985613
I think the existing permissions may have been set due to 
https://github.com/falconindy/pkgfile/blob/v17/Makefile.am#L88 
But I don't know Arch's packaging system.

Anyway, it would seem that pkgfile should decide if 0775 or 0755 is
correct and fix things up rather than have many users have to work out
what to change it to manually, and wonder if that's the right thing for
them to do.

**Comment by falconindy** [comment]
Yes, f39b715b9498d977269e16941b23d916c1985613 would be responsible for this diff. I don't know why I originally made the directory 775 instead of 755, and the commit adding this isn't helpful (f39b715b9498d977269e16941b23d916c1985613).

Without any context, I'm inclined to leave it as 755. I can't see any good reason why there would be more than one writer for the cache.

**Comment by RalphCorderoy** [comment]
Given the owner:group is root:root I don't think one or more 'root' writers matters.
But now 0755 has been settled on, can we please have the next upgrade of the pkgfile package fix the historic 0775 so all those users don't have to spend time investigating a `pacman -Qkk` error.

**Comment by falconindy** [comment]
Sure, but that's not a Github concern. See Arch's pkgfile-18-2
