### ISSUE TITLE
Should `command_not_found_handle` return 0?

### ISSUE THREAD

**Issue by CyberShadow** [falconindy/pkgfile#43]
This is pretty much a cosmetic issue, but, it's a bit weird how the "exit status" of a non-existing command changes depending on whether `command_not_found_handle` finds a package with said command or not. Executing the command that the user typed does not succeed either way, so, I think the exit status should be 127 in both cases.

The lines in question:
https://github.com/falconindy/pkgfile/blob/006e213ffc700fe4626220b9991106924d8bcf42/extra/command-not-found.bash#L23
https://github.com/falconindy/pkgfile/blob/006e213ffc700fe4626220b9991106924d8bcf42/extra/command-not-found.zsh#L8

**Comment by falconindy** [comment]
Yep, makes sense. Thanks for reporting.
