### ISSUE TITLE
/var/cache/pkgfile/community.files: Win.Trojan.Maljava-2 FOUND -- false positive?

### ISSUE THREAD

**Issue by wiemag** [falconindy/pkgfile#46]
$ clamscan --max-filesize=200M --max-scansize=200M /var/cache/pkgfile/community.files 
/var/cache/pkgfile/community.files: Win.Trojan.Maljava-2 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 6110477
Engine version: 0.101.2
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 138.23 MB
Data read: 169.26 MB (ratio 0.82:1)
Time: 211.158 sec (3 m 31 s)

Running the same command without --max-filesize and --max-scansize does not report community.files as infected, but no scanning is made.
I removed community.files and downloaded them back with pkgfile -u.
Reported as "Infected" again.

**Comment by falconindy** [comment]
Uh, it's a compressed cpio archive of text files.

**Comment by saltedcoffii** [comment]
This still seems to be an issue.

**Comment by saltedcoffii** [comment]
it seems to be specifically the metasploit file (I have metasploit-6.2.0-2). I'm opening a false-positive report with ClamAV, for anyone else coming across this issue. I hope they fix it soon.

**Comment by saltedcoffii** [comment]
They appear to have fixed it.
