### ISSUE TITLE
systemd service fails to update with no error

### ISSUE THREAD

**Issue by fdservices** [falconindy/pkgfile#49]
Oct 03 08:23:34 acer pkgfile[128503]: warning: download failed: http://mirrors.manchester.m247.com/arch-linux/multilib/>
Oct 03 08:23:34 acer pkgfile[128503]: warning: download failed: https://mirror.thekinrar.fr/archlinux/multilib/os/x86_6>
Oct 03 08:23:34 acer pkgfile[128503]: warning: download failed: http://mirror.oldsql.cc/archlinux/core/os/x86_64/core.f>
Oct 03 08:23:34 acer pkgfile[128503]: error: failed to update repo: core
Oct 03 08:23:34 acer pkgfile[128503]: warning: download failed: https://mirror.thekinrar.fr/archlinux/community/os/x86_>
Oct 03 08:23:34 acer pkgfile[128503]: warning: download failed: http://mirror.oldsql.cc/archlinux/multilib/os/x86_64/mu>
Oct 03 08:23:34 acer pkgfile[128503]: error: failed to update repo: multilib
Oct 03 08:23:34 acer systemd[1]: Starting pkgfile database update...
Oct 03 08:23:34 acer systemd[1]: pkgfile-update.service: Succeeded.
Oct 03 08:23:34 acer systemd[1]: Started pkgfile database update.

**Comment by falconindy** [comment]
This is #47.

**Comment by fdservices** [comment]
Yes, sorry, I thought I remembered an update since v19.1
