### ISSUE TITLE
--update exits with 1 when everything is up-to-date

### ISSUE THREAD

**Issue by grawity** [falconindy/pkgfile#50]
As of pkgfile v20-1, `pkgfile -u` will report failure even when everything is already up-to-date, annoying me with cronmail:

```
# pkgfile -u
:: Updating 9 repos...
  gnome-unstable is up to date
  multilib-testing is up to date
  testing is up to date
  core is up to date
  extra is up to date
  community-testing is up to date
  community is up to date
  multilib is up to date
  heftig is up to date
(returned 1)

# echo $?
1
```

It doesn't do so when any updates have actually been downloaded, so in the mean time I just use `-uu` to force a re-download.

**Comment by falconindy** [comment]
Thanks for the report! 87186eb should resolve this, and provides some sad history of how we got here.

**Comment by Maryse47** [comment]
@falconindy could you made a bugfix release with this commit? It's annoying that this service constantly reports failure. You may also pull https://github.com/falconindy/pkgfile/pull/51
