### ISSUE TITLE
Problems with systemd service

### ISSUE THREAD

**Issue by fdservices** [falconindy/pkgfile#52]
Thanks for the latest update. If I enable the sytemd service on my laptop then the update will fail on the first run of the day, because the network takes a short time to connect. As it is set up, it only tries to run the update once. Also, I note that if the update does run and all the files are already up to date, then it returns an error code 1, which would probably indicate to systemd that it had failed.

**Comment by falconindy** [comment]
This is 3fe6402d6a4f915f84bd7978cc3888a051147d4f

**Comment by fdservices** [comment]
Requires a wait-online.service which is not appropriate on my laptop.

**Comment by falconindy** [comment]
Enable the timer, not the service

**Comment by fdservices** [comment]
I thought that the pkgfile-update.timer file activates and controls the pkgfile-update.service. The new service file includes 
`After=network-online.target`
`Wants=network-online.target` 
which in turn require a wait-online.service which is not appropriate on my laptop.  ([https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/](url)

**Comment by falconindy** [comment]
@medhefgo since they're responsible for the network stuff.

IMO, you can:

1) Use cron instead
2) Override the settings in the unit
3) Submit a pull request with changes to the timer such that it's more suitable for not-always-on machines.

**Comment by falconindy** [comment]
I have no idea why that changes your ability to make changes to the timer. It's a fixed bug, regardless. Assume pkgfile exits 0 for the up to date case.

**Comment by fdservices** [comment]
OK, thank you.

**Comment by fdservices** [comment]
Here is my suggested service file. It will try four times, at 15 second intervals, to update pkgfile. This should be enough time for the network to come up and does not require a wait-online.service:

`[Unit]
Description=pkgfile database update
RequiresMountsFor="/var/cache/pkgfile"
StartLimitIntervalSec=65
StartLimitBurst=4

[Service]
Type=simple
ExecStart=/usr/bin/pkgfile -u
Nice=19
Restart=on-failure
RestartSec=15
StandardOutput=null
StandardError=journal
PrivateTmp=yes
PrivateDevices=yes
CapabilityBoundingSet=
NoNewPrivileges=yes`

**Comment by medhefgo** [comment]
What's wrong with relying on network-online.target? It's designed for this kind of thing. Also, your service is no solution to not-always-on machines. What happens if wifi connection doesn't come up for hours later?

**Comment by fdservices** [comment]
I did add this link before: 
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

It is worth reading if you haven't already done so.

> The right "wait" service must be enabled too 
> (NetworkManager-wait-online.service if NetworkManager is used to 
> configure the network, systemd-networkd-wait-online.service if 
> systemd-networkd is used, etc.)
That alone lets me out.

the network-online.target
> will ensure that all configured network devices are up and have an IP 
> address assigned before the service is started. network-online.target 
> will time out after 90s. Enabling this might considerably delay your 
> boot even if the timeout is not reached.
So there does not seem to be much difference to mu suggestion except 
that there will be no delay on boot.

If the wifi connection does not come up for hours then the timer will 
still retry the service every 24 hours.

Andrew

**Comment by medhefgo** [comment]
Having pkgfile.timer pull in pkgfile.service during boot should not delay multi-user.target. If it does, then you probably have some dependencies wrong. You aren't supposed to enable pkgfile.service directly for this.

Also, what happens if one were extra lucky and wifi is never around when the timer happen to trigger?
The correct solution would be to poll in ~15min intervals or so within pkgfile itself. Otherwise the netwok-online.target is the next best option.

**Comment by fdservices** [comment]
You are right, I think. The correct solution would be for pkgfile itself 
to provide the solution. Another quote from the freedesktop.org article:
> If you are a developer, instead of wondering what to do about 
> network.target, please just fix your program to be friendly to 
> dynamically changing network configuration. That way you will make 
> your users happy because things just start to work, and you will get 
> fewer bug reports as your stuff is just rock solid. You also make the 
> boot faster for your users, as they don't have to delay arbitrary 
> services for the network anymore
Otherwise there are now two solutions available.

**Comment by falconindy** [comment]
Next version of pkgfile will have a no-network solution for this (see the cpp branch). Not interested in changing this unit any further
