### ISSUE TITLE
command-not-found handler doesn't find binaries from /usr/bin/vendor_perl/

### ISSUE THREAD

**Issue by VorpalBlade** [falconindy/pkgfile#60]
I recently happend to discover that the zsh command-not-found handler does not find binaries located in `/usr/bin/vendor_perl/`, such as `exiftool`. Presumably the same issue exists for `/usr/bin/core_perl/` though I have not verified this.

Looking at zsh script I believe the issue is in pkgfile itself though.

**Comment by stepnem** [comment]
> Looking at zsh script I believe the issue is in pkgfile itself though.

Yes, you can easily verify that using `pkgfile -b`.

`pkgfile` built from current master doesn't have that problem, though,
so the Arch repo version is just old (IOW, @falconindy probably needs
to cut a new release).
