### ISSUE TITLE
systemd service fails with local repo (#53)

### ISSUE THREAD

**Issue by Strykar** [falconindy/pkgfile#64]
I have the same issue as https://github.com/falconindy/pkgfile/issues/53 and the suggested fix in that issue does not appear to work:
```
Oct 29 15:07:16 i-5 systemd[1]: Starting pkgfile database update...
Oct 29 15:07:16 i-5 pkgfile[338710]: warning: download failed: file:///home/strykar/arch_packages/aurpkgs/aurpkgs.files: Couldn't open file /home/strykar/arch_packages/aurpkgs/aurpkgs.files
Oct 29 15:07:16 i-5 pkgfile[338710]: error: failed to update repo: aurpkgs
Oct 29 15:07:16 i-5 systemd[1]: pkgfile-update.service: Main process exited, code=exited, status=1/FAILURE
Oct 29 15:07:16 i-5 systemd[1]: pkgfile-update.service: Failed with result 'exit-code'.
```
```
# cat /etc/systemd/system/pkgfile-update.service.d/override.conf
[Service]
ReadOnlyPaths=/home/strykar/arch_packages
```
What are we missing here?
Snipped `pacman.conf`:
```
[aurpkgs]
SigLevel = Optional TrustAll
Server = file:///home/strykar/arch_packages/aurpkgs
```

**Comment by falconindy** [comment]
Do you actually have a aurpkgs.files, or just aurpkgs.db?

**Comment by falconindy** [comment]
Was able to reproduce this. The empty `CapabilityBoundingSet` seems to be preventing access, but I'll have to dig deeper to understand what cap is actually needed.

**Comment by falconindy** [comment]
Ok, understood. root usually has `CAP_DAC_OVERRIDE`, which is what allows it to ignore permissions and traverse/read/write anything it wants. Without that cap, root is no different from any other user. It's likely that your $HOME is mode 700, which prevents root from accessing anything underneath it. I'll let you decide how to solve that. Some options, in no particular order:

* [worst] Add CAP_DAC_OVERRIDE to the unit
* [bad] Make your $HOME mode 755
* [good] move your repo somewhere outside of $HOME.
