### ISSUE TITLE
Still showing `community` repo

### ISSUE THREAD

**Issue by mlmatlock** [falconindy/pkgfile#66]
```
$ pkgfile /usr/bin/tqdm
community/python-tqdm
extra/python-tqdm
```
```
$ pkgfile lostfiles
community/lostfiles
extra/lostfiles
```
Probably more...

**Comment by falconindy** [comment]
So, pkgfile doesn't parse pacman.conf at startup to determine what repos to read from. It just finds anything matching *.files in its cache directory. There's a mix of historical and performance reasons for this.

Ultimately it's up to you to delete the community.files DB from disk, though.
