### ISSUE TITLE
Behavior of -d changed from also including directories to only including directories

### ISSUE THREAD

**Issue by darlingm** [falconindy/pkgfile#67]
68b4ce5 changed the behavior of `-d`, from previously also including directories in the results to only including directories in results.  In other words, previously, this would work:

    $ pkgfile -d /usr/bin/vim
    extra/gvim
    extra/vim

But, v22 no longer shows anything as output.

I have a script that automatically uses `-di`, otherwise I'd of course never type it this way.

If this is an intentional change, I'll be happy to change my script.  (In that situation, the manpage and `--help` could include `only`.)  Thanks for the program!

**Comment by falconindy** [comment]
Interesting. /usr/bin/vim isn't a directory, so I don't know that I'd expect this to output anything. In that regard, the commit you cite feels like a fix.

Let's see what the manpage has to say:

```
Match directories in search results.
```

Hmm, not terribly specific, I agree.

If you add -v, what does this match in the previous version?

**Comment by falconindy** [comment]
Noting for myself that the previous implementation doesn't look obviously buggy, and the intent seems clear that it *adds* directories to the output.

**Comment by falconindy** [comment]
Well, we can't remove -d because it's unclear what the user intent is when used with --list.

I think the summary here is that the change is:

* Unintended side effect
* Unclear historical intent

So now 5 years after that commit, I'm left to just figure out if this is the right thing to do or not. Could you explain a bit more about how you're using pkgfile in your script?

**Comment by darlingm** [comment]
Sure, if there's a single argument that doesn't start with a dash, it updates if it's been over an hour since the last one, then passes the argument using `-di`.  Otherwise, it just passes the arguments through.  I can easily change it to conditionally use `-d` if the single argument ends with `/`, so no biggie either way.

I write a lot of wrappers for things.  This is named `pkgfile-helper.sh`, and `pkgfile` is aliased to it only if it's a user's terminal.

```
#!/usr/bin/bash

TIMESTAMP_FILE="/var/cache/pkgfile/.update_timestamp"

if [[ "$#" -eq 1 && "$1" != -* ]]; then
    if [[ -f "$TIMESTAMP_FILE" ]]; then
        current_time=$(date +%s)
        last_update_time=$(stat -c %Y "$TIMESTAMP_FILE")

        time_diff=$((current_time - last_update_time))
    fi

    if [[ ! -v time_diff || "$time_diff" -gt 3600 ]]; then
        echo "Updating pkgfile database..."
        sudo pkgfile --update
        sudo touch "$TIMESTAMP_FILE"
    fi

    pkgfile -di "$1"
else
    pkgfile "$@"
fi
```

**Comment by falconindy** [comment]
Thinking about this a little more, the previous behavior of -d made more sense. Currently it isn't possible to list the full contents of a package, as -d acts as a toggle between files and directories. For the search case, you're probably also right that a trailing / should imply a directory search, but I'll have to write some tests to convince myself I wouldn't be breaking something if I did that.

I'll get this fixed, but I'm on vacation right now and it'll be at least a week before I'm back home.

Semi-related: it's not terribly well documented yet, but you might be interested in pkgfiled, which updates pkgfile caches whenever pacman files DBs are updated. That would save you from the awkward privilege escalation in your script.

Thanks for the report. Glad pkgfile is useful to you.
