### ISSUE TITLE
Docs: Add info that aur is not supported

### ISSUE THREAD

**Issue by KAGEYAM4** [falconindy/pkgfile#70]
I was underimpression that this would work on aur too. But it didn't and `pacman -Qo <file-name` was working. So i thought it maybe a bug. I read the man page but still not clear. Then finally on this repo i first searched issues and got to know how this works and why aur is not supported.

My point is that for beginners, making it clear that Aur package support is out of scope for this project. Somewhere in Readme or man page would be helpful.

**Comment by falconindy** [comment]
> But it didn't and pacman -Qo <file-name was working.

But that isn't the point of pkgfile. If `pacman -Qo` handled uninstalled packages, there'd be little reason for pkgfile to exist. In fact, that's the whole reason pacman -F 

> I was underimpression that this would work on aur too.

Was that an assumption? What docs did you read first before coming to that conclusion? The README has a few clues here already:

- `pkgfile is targetted at Arch Linux users and depends on the .files databases served by package mirrors.` -- the AUR isn't a package mirror and does not serve `.files` DBs.
- `pkgfile differs from the functionality of pacman -F` -- but doesn't go on to say that this includes the AUR. Do you expect pacman -F to handle the AUR?

...and the package description in Arch Linux further draws a strong connection to .files databases.

Please help me understand your thought process here so we can fix this in the right place.

**Comment by KAGEYAM4** [comment]
1. From here https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Utilities - `Tool that finds what package owns a file.`
2. The description above was enough for me too not look at actual package description provided in ArchRepo.
3. Then i just used --help and tried running it and it worked. It always worked, luckily i was always trying it on official repo packages
4. But when i tried on a binary belonging to aur, which i did not know was from aur. It didn't worked.
5. I looked at man page grossed over terms like `.files metadata created by repo-add(8)`, and found some interesting things like bash-function along with automating updates.
6. still didn't understand
7. After opening this project repo, the Readme made it clear and i understood how this package worked. 
8. i also did a search in issue for `aur` just to see if it could be implemented.

**Comment by falconindy** [comment]
So let's fix the wiki, right? That's not owned or maintained by me.
